# при повторном запуске необходимо убедиться, что каталог
# ./database/data пуст
version: "3"

services:

  confluence:
    image: postgres:11
    container_name: postgres-forum
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0a610292api
      POSTGRES_DB: forum
    logging:
      # логи доступны на хосте по команде docker logs postgres-forum
      driver: json-file
      options:
        tag: postgres-forum
    volumes:
      - ./db/database/data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5430:5432"

  forum_api:
    image: forum_api:latest
    container_name: forum-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: confluence
      DB_PORT: 5432
    logging:
      driver: json-file
      options:
        tag: forum_api
    ports:
      - "8080:8080"
    command:
      "python3 /tmp/src/forum_api/forum_api/main.py"
